const GLOSS_ABREV = {
    "1": "1st Person",
    "1P": "1st Person",
    "1PL": "1st Person Plural",
    "1SG": "1st Person Singular",
    "2": "2nd Person",
    "2P": "2nd Person",
    "2PL": "2nd Person Plural",
    "2SG": "2nd Person Singular",
    "3": "3rd Person",
    "3P": "3rd Person",
    "3PL": "3rd Person Plural",
    "3SG": "3rd Person Singular",
    "ABL": "Ablative",
    "ABS": "Absolutive",
    "ACC": "Accusative",
    "ACT": "Active",
    "ADJ": "Adjective",
    "ADV": "Adverbial",
    "AGR": "Agreement",
    "ANIM": "Animate",
    "ANTIP": "Antipassive",
    "AOR": "Aorist",
    "APPL": "Applicative",
    "ART": "Article",
    "AUG": "Augmentative",
    "AUX": "Auxiliary",
    "BEN": "Benefactive",
    "C": "Common",
    "CAUS": "Causative",
    "CL": "Classifier",
    "COL": "Collective",
    "COM": "Comitative",
    "COMP": "Complement",
    "COMPL": "Completive",
    "COND": "Conditional",
    "CONJ": "Conjunctive",
    "CONT": "Continuous",
    "COP": "Copula",
    "CVB": "Converb",
    "DAT": "Dative",
    "DECL": "Declarative",
    "DEF": "Definite",
    "DEM": "Demonstrative",
    "DEO": "Deontic",
    "DET": "Determiner",
    "DIM": "Diminutive",
    "DIR": "Direct",
    "DIST": "Distal",
    "DS": "Different Subject",
    "DU": "Dual",
    "DO": "Different Object",
    "DUB": "Dubitative",
    "DUR": "Durative",
    "EGO": "Egophoric",
    "ERG": "Ergative",
    "EV": "Evidential",
    "EXC": "Exclusive",
    "EXCL": "Exclusive",
    "F": "Feminine",
    "FOC": "Focus",
    "FUT": "Future",
    "GEN": "Genitive",
    "GER": "Gerund",
    "GNO": "Gnomic",
    "H": "Human",
    "HAB": "Habitual",
    "HON": "Honorific",
    "HORT": "Hortative",
    "HYP": "Hypotetical",
    "IMM": "Immediate",
    "IMP": "Imperative",
    "IMPF": "Imperfect",
    "INAN": "Inanimate",
    "INC": "Inclusive",
    "INCL": "Inclusive",
    "IND": "Indicative",
    "INDEF": "Indefinite",
    "INF": "Infinitive",
    "INST": "Instrumental",
    "INT": "Interrogative",
    "INTR": "Intransitive",
    "INV": "Inverse",
    "IPFV": "Imperfective",
    "IRR": "Irrealis",
    "LAT": "Lative",
    "LOC": "Locative",
    "M": "Masculine",
    "MID": "Middle",
    "MED": "Medial",
    "N": "Neuter",
    "NANIM": "Inanimate",
    "NDEF": "Indefinite",
    "NEG": "Negative",
    "NFUT": "Non-Future",
    "NMLZ": "Nominalized",
    "NOM": "Nominative",
    "NPERF": "Imperfect",
    "NPFV": "Imperfective",
    "NPRES": "Non-Present",
    "NPRF": "Imperfect",
    "NPRS": "Non-Present",
    "NPST": "Non-Past",
    "NSPEC": "Nonspecific",
    "NTR": "Intransitive",
    "NUM": "Numeral",
    "OBJ": "Object",
    "OBL": "Oblique",
    "OBQ": "Oblique",
    "PART": "Partitive",
    "PASS": "Passive",
    "PERF": "Perfect",
    "PFV": "Perfective",
    "PL": "Plural",
    "POL": "Polite",
    "POSS": "Possessive",
    "PRED": "Predicative",
    "PREP": "Prepositional",
    "PRES": "Present",
    "PRET": "Preterit",
    "PRF": "Perfect",
    "PRO": "Pronominal",
    "PROG": "Progressive",
    "PROH": "Prohibitive",
    "PROP": "Propositional",
    "PROX": "Proximal",
    "PRS": "Present",
    "PST": "Past",
    "PTCP": "Participle",
    "PURP": "Purposive",
    "QUOT": "Quotative",
    "REAL": "Realis",
    "REC": "Recent",
    "RECP": "Reciprocal",
    "REFL": "Reflexive",
    "REL": "Relative",
    "REM": "Remote",
    "RES": "Resultative",
    "SBJ": "Subject",
    "SBJV": "Subjunctive",
    "SEQ": "Sequential",
    "SER": "Serial",
    "SG": "Singular",
    "SML": "Similative",
    "SPEC": "Specific",
    "SS": "Same Subject",
    "SO": "Same Object",
    "STAT": "Stative",
    "SUP": "Supine",
    "TOP": "Topic",
    "TR": "Transitive",
    "VAL": "Valence",
    "VOC": "Vocative",
}

function abrev(tag) {
    return tag.split('.').map(t => GLOSS_ABREV[t] ?? t).join(' ')
}