const GLOSS_ABREV = {
    "1": "1st Person",
    "2": "2nd Person",
    "3": "3rd Person",
    "4": "4th Person",
    "A": "Agent",
    "ABL": "Ablative",
    "ABS": "Absolutive",
    "AC": "Anticausative",
    "ACC": "Accusative",
    "ACT": "Active",
    "ADJ": "Adjective",
    "ADV": "Adverbial",
    "AF": "Agent Focus",
    "AFF": "Affirmative",
    "AGR": "Agreement",
    "AL": "Alienable",
    "ALL": "Allative",
    "ANIM": "Animate",
    "ANTIC": "Anticausative",
    "ANTIP": "Antipassive",
    "AOR": "Aorist",
    "AP": "Antipassive",
    "APPL": "Applicative",
    "APRX": "Approximative",
    "ART": "Article",
    "AUD": "Auditory Evidential",
    "AUG": "Augmentative",
    "AUX": "Auxiliary",
    "BEN": "Benefactive",
    "BF": "Beneficiary Focus",
    "C": "Common",
    "CAUS": "Causative",
    "CF": "Circumstantial Focus",
    "CL": "Classifier",
    "CMP": "Comparative",
    "COL": "Collective",
    "COM": "Comitative",
    "COMP": "Complement",
    "COMPL": "Completive",
    "COND": "Conditional",
    "CONJ": "Conjunctive",
    "CONS": "Construct",
    "CONT": "Continuous",
    "CONTR": "Constrastive",
    "CONV": "Converb",
    "COORD": "Coordination",
    "COP": "Copula",
    "CQ": "Content Question",
    "CTFG": "Centrifugal",
    "CTPT": "Centripetal",
    "CVB": "Converb",
    "DAT": "Dative",
    "DECL": "Declarative",
    "DED": "Dedutive Evidential",
    "DEF": "Definite",
    "DEM": "Demonstrative",
    "DEO": "Deontic",
    "DES": "Desiderative",
    "DET": "Determiner",
    "DIM": "Diminutive",
    "DIR": "Direct",
    "DIST": "Distal",
    "DO": "Different Object",
    "DS": "Different Subject",
    "DU": "Dual",
    "DUB": "Dubitative",
    "DUR": "Durative",
    "DYN": "Dynamic",
    "EGO": "Egophoric",
    "ELA": "Elative",
    "EMP": "Emphatic",
    "ERG": "Ergative",
    "ESS": "Essive",
    "EV": "Evidential",
    "EX": "Exclusive",
    "EXC": "Exclusive",
    "EXCL": "Exclusive",
    "EXP": "Experiential Evidential",
    "F": "Feminine",
    "FACT": "Factive",
    "FEM": "Feminine",
    "FIN": "Finite",
    "FN": "Finite",
    "FOC": "Focus",
    "FREQ": "Frequentative",
    "FUT": "Future",
    "GEN": "Genitive",
    "GER": "Gerund",
    "GF": "Goal Focus",
    "GNO": "Gnomic",
    "H": "Human",
    "HAB": "Habitual",
    "HON": "Honorific",
    "HORT": "Hortative",
    "HUM": "Human",
    "HYP": "Hypothetical",
    "IDEO": "Ideophone",
    "IF": "Instrument Focus",
    "IMM": "Immediate",
    "IMP": "Imperative",
    "IMPF": "Imperfect",
    "IN": "Inclusive",
    "INAC": "Inactive",
    "INAL": "Inalienable",
    "INAN": "Inanimate",
    "INC": "Inclusive",
    "INCEP": "Inceptive",
    "INCH": "Inchoative",
    "INCL": "Inclusive",
    "IND": "Indicative",
    "INDEF": "Indefinite",
    "INDET": "Indeterminate",
    "INDIR": "Indirect",
    "INF": "Infinitive",
    "INFER": "Inferential",
    "INFL": "Inflection",
    "INS": "Instrumental",
    "INST": "Instrumental",
    "INT": "Interrogative",
    "INTENS": "Intensive",
    "INTER": "Interrogative",
    "INTERJ": "Interjection",
    "INTJ": "Interjection",
    "INTR": "Intransitive",
    "INV": "Inverse",
    "IO": "Indirect Object",
    "IPFV": "Imperfective",
    "IRR": "Irrealis",
    "ITER": "Iterative",
    "JUS": "Jussive",
    "LAT": "Lative",
    "LOC": "Locative",
    "M": "Masculine",
    "MAL": "Malefactive",
    "MASC": "Masculine",
    "MED": "Medial",
    "MID": "Middle",
    "N": "Neuter",
    "NANIM": "Inanimate",
    "NARR": "Narrative",
    "NDEF": "Indefinite",
    "NEG": "Negative",
    "NEUT": "Neuter",
    "NF": "Infinitive",
    "NFIN": "Infinitive",
    "NFUT": "Non-Future",
    "NH": "Non-Human",
    "NHUM": "Non-Human",
    "NMLZ": "Nominalized",
    "NOM": "Nominative",
    "NPERF": "Imperfect",
    "NPFV": "Imperfective",
    "NPRES": "Non-Present",
    "NPRF": "Imperfect",
    "NPRS": "Non-Present",
    "NPST": "Non-Past",
    "NSPEC": "Nonspecific",
    "NTR": "Intransitive",
    "NUM": "Numeral",
    "O": "Object",
    "OBJ": "Object",
    "OBL": "Oblique",
    "OBQ": "Oblique",
    "OBV": "Obviate",
    "OF": "Object Focus",
    "OPT": "Optative",
    "ORD": "Ordinal",
    "PART": "Partitive",
    "PASS": "Passive",
    "PAU": "Paucal",
    "PERF": "Perfect",
    "PF": "Patient Focus",
    "PFV": "Perfective",
    "PLUP": "Pluperfect",
    "POL": "Polite",
    "POSS": "Possessive",
    "PQ": "Polar Question",
    "PRED": "Predicative",
    "PREP": "Prepositional",
    "PRES": "Present",
    "PRET": "Preterit",
    "PRF": "Perfect",
    "PRO": "Pronominal",
    "PROG": "Progressive",
    "PROH": "Prohibitive",
    "PROP": "Propositional",
    "PROX": "Proximal",
    "PRS": "Present",
    "PSR": "Possessor",
    "PST": "Past",
    "PTCP": "Participle",
    "PTV": "Partitive",
    "PURP": "Purposive",
    "Q": "Question",
    "QUOT": "Quotative",
    "REAL": "Realis",
    "REC": "Recent",
    "RECP": "Reciprocal",
    "REF": "Referential",
    "REFL": "Reflexive",
    "REL": "Relative",
    "REM": "Remote",
    "RES": "Resultative",
    "S": "Subject",
    "SBJ": "Subject",
    "SBJV": "Subjunctive",
    "SEM": "Semelfactive",
    "SEQ": "Sequential",
    "SER": "Serial",
    "SG": "Singular",
    "SIM": "Simultaneous",
    "SJV": "Subjunctive",
    "SML": "Similative",
    "SO": "Same Object",
    "SPEC": "Specific",
    "SS": "Same Subject",
    "STAT": "Stative",
    "SUP": "Supine",
    "SUPL": "Superlative",
    "TOP": "Topic",
    "TR": "Transitive",
    "TRI": "Trial",
    "V": "Verb",
    "VAL": "Valence",
    "VERB": "Verb",
    "VN": "Verbal Noun",
    "VOC": "Vocative",
    "VOL": "Volitive",
}

function abrev(tag) {
    if (+tag[0]>0&&+tag[0]<=4) tag = tag[0]+'.'+tag.slice(1);
    return tag.split('.').map(t => GLOSS_ABREV[t] ?? t).join(' ');
}